apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
  labels:
    app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 5
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Parser docker
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
        Refresh_Interval 10

    [INPUT]
        Name systemd
        Tag systemd.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

    [FILTER]
        Name kubernetes
        Match kube.*
        Kube_URL https://kubernetes.default.svc:443
        Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix kube.var.log.containers.
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Labels On
        Annotations Off

    [FILTER]
        Name parser
        Match kube.*user-service*
        Key_Name log
        Parser go-json
        Reserve_Data On
        Preserve_Key On

    [FILTER]
        Name parser
        Match kube.*auth-service*
        Key_Name log
        Parser node-json
        Reserve_Data On
        Preserve_Key On

    [FILTER]
        Name parser
        Match kube.*notification-service*
        Key_Name log
        Parser python
        Reserve_Data On
        Preserve_Key On

    [FILTER]
        Name parser
        Match kube.*analytics-service*
        Key_Name log
        Parser java
        Reserve_Data On
        Preserve_Key On

    [FILTER]
        Name modify
        Match *
        Add cluster devsecops
        Add environment ${ENVIRONMENT}

    [FILTER]
        Name throttle
        Match *
        Rate 1000
        Window 5
        Interval 1s

    [FILTER]
        Name grep
        Match kube.*
        Exclude kubernetes_namespace_name kube-system|kube-public|kube-node-lease

    [OUTPUT]
        Name cloudwatch_logs
        Match kube.*devsecops*
        region us-east-1
        log_group_name /aws/eks/devsecops/application
        log_stream_prefix ${HOSTNAME}-
        auto_create_group On

    [OUTPUT]
        Name cloudwatch_logs
        Match systemd.*
        region us-east-1
        log_group_name /aws/eks/devsecops/system
        log_stream_prefix ${HOSTNAME}-
        auto_create_group On

  custom_parsers.conf: |
    [PARSER]
        Name go-json
        Format json
        Time_Key timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ

    [PARSER]
        Name node-json
        Format json
        Time_Key timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ

    [PARSER]
        Name python
        Format regex
        Regex ^(?<time>[^ ]+ [^ ]+) (?<level>[^ ]+) \[(?<service>[^\]]+)\] (?<message>.*)$
        Time_Key time
        Time_Format %Y-%m-%d %H:%M:%S,%L

    [PARSER]
        Name java
        Format multiline
        Multiline_Pattern ^\d{4}-\d{2}-\d{2}
        Multiline_Key_Content log
