FROM maven:3.9-eclipse-temurin-17

WORKDIR /app

# Copy pom.xml and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copy source code
COPY src ./src

EXPOSE 8084

CMD ["mvn", "spring-boot:run"]
