apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-templates
  namespace: monitoring
data:
  slack.tmpl: |
    {{ define "slack.default.title" }}
    [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.alertname }}
    {{ end }}

    {{ define "slack.default.text" }}
    {{ range .Alerts }}
    *Alert:* {{ .Labels.alertname }}
    *Severity:* {{ .Labels.severity }}
    *Service:* {{ .Labels.service | default "N/A" }}
    *Namespace:* {{ .Labels.namespace | default "N/A" }}
    *Summary:* {{ .Annotations.summary }}
    *Description:* {{ .Annotations.description }}
    *Started:* {{ .StartsAt.Format "2006-01-02 15:04:05 MST" }}
    {{ if .EndsAt }}*Ended:* {{ .EndsAt.Format "2006-01-02 15:04:05 MST" }}{{ end }}
    {{ end }}
    {{ end }}

  email.tmpl: |
    {{ define "email.html" }}
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background-color: {{ if eq .Status "firing" }}#d32f2f{{ else }}#388e3c{{ end }}; color: white; padding: 20px; text-align: center; }
        .alert { border-left: 4px solid {{ if eq .Status "firing" }}#d32f2f{{ else }}#388e3c{{ end }}; padding: 15px; margin: 10px 0; background-color: #f5f5f5; }
        .label { font-weight: bold; }
        .footer { margin-top: 20px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #666; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>{{ .Status | toUpper }} Alert: {{ .GroupLabels.alertname }}</h1>
        </div>
        {{ range .Alerts }}
        <div class="alert">
          <p><span class="label">Alert:</span> {{ .Labels.alertname }}</p>
          <p><span class="label">Severity:</span> {{ .Labels.severity }}</p>
          <p><span class="label">Service:</span> {{ .Labels.service | default "N/A" }}</p>
          <p><span class="label">Namespace:</span> {{ .Labels.namespace | default "N/A" }}</p>
          <p><span class="label">Summary:</span> {{ .Annotations.summary }}</p>
          <p><span class="label">Description:</span> {{ .Annotations.description }}</p>
          <p><span class="label">Started:</span> {{ .StartsAt.Format "2006-01-02 15:04:05 MST" }}</p>
          {{ if .EndsAt }}<p><span class="label">Ended:</span> {{ .EndsAt.Format "2006-01-02 15:04:05 MST" }}</p>{{ end }}
        </div>
        {{ end }}
        <div class="footer">
          <p>This alert was generated by AlertManager for the DevSecOps Platform</p>
          <p>View in Prometheus: <a href="{{ .ExternalURL }}">{{ .ExternalURL }}</a></p>
        </div>
      </div>
    </body>
    </html>
    {{ end }}
