apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devsecops-dev
  source:
    repoURL: https://github.com/khaledhawil/DevSecOps-Project.git
    targetRevision: main
    path: 04-kubernetes/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: devsecops-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devsecops-dev
  source:
    repoURL: https://github.com/khaledhawil/DevSecOps-Project.git
    targetRevision: main
    path: 04-kubernetes/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: devsecops-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-service-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devsecops-dev
  source:
    repoURL: https://github.com/khaledhawil/DevSecOps-Project.git
    targetRevision: main
    path: 04-kubernetes/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: devsecops-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: analytics-service-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devsecops-dev
  source:
    repoURL: https://github.com/khaledhawil/DevSecOps-Project.git
    targetRevision: main
    path: 04-kubernetes/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: devsecops-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devsecops-dev
  source:
    repoURL: https://github.com/khaledhawil/DevSecOps-Project.git
    targetRevision: main
    path: 04-kubernetes/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: devsecops-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10
