apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devsecops-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/khaledhawil/DevSecOps-Project.git
    targetRevision: main
    path: 05-cicd/argocd/applications
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
