apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  db-host: "devsecops-dev-postgres.xxxxx.us-east-1.rds.amazonaws.com"
  db-port: "5432"
  db-name: "devsecops_dev"
  redis-host: "devsecops-dev-redis.xxxxx.cache.amazonaws.com"
  redis-port: "6379"
  log-level: "info"
  rate-limit: "100"
